name: FastLeafDecay
version: ${project.version}
main: com.cavetale.fastleafdecay.FastLeafDecayPlugin
api-version: '1.13'
description: Speed up Leaf Decay
author: StarTux
website: https://cavetale.com
