name: Java CI
on: [ push, pull_request ]

jobs:
  build-java-11:
    uses: okocraft/workflows/.github/workflows/maven.yml@v1
    with:
      java-version: '11'
      package-name: FastLeafDecay-Build-${{ github.run_number }}
